### PR TITLE
[stPagination] externally-set numberOfPages attribute addition

### PR DESCRIPTION
**Pull request by matgardon**
Proposed addition of a "stNumberOfPages" attribute to stPagination to
handle externally-set total number of pages, in srv-side data fetching
scenarios. It internally updates the tableState.pagination.numberOfPages
property.

### CODE REVIEW

**Comment by lorenzofox3** [comment]
Hello,
this should already be handled by your custom pipe function as explained on the [documentation website](http://lorenzofox3.github.io/smart-table-website/#section-pipe). 
If not, then it means you are using a client side table and the numberOfPages would be the result of a calculation based on the number of items to display by page and your dataset size

thanks a lot for your contribution

**Comment by matgardon** [comment]
Hi, 

Im may be wrong but I do believe this scenario is not yet handled.

You argue that it should be handled by my custom pipe function, which is true for events that happen inside the smart-table (such as page changes etc). 

But what about external events that should trigger the pipe function ? In this case, I can't call my pipe function with the tableState object, so I have no external way of setting the total number of pages (which in turn should trigger the corresponding reload).

I would argue that such use cases are fairly common : If I have a table that should refetch from the server it's data-set depending on the current user role, then on a user-role change (external to the table scope), I should be able to call the pipe function to reload my table with new data, but it's still a server-side table and not a client-side table (as only the data from the server contextually changed), so I shouldn't have to manually handle a client-side data table and take care of all the server-side plumbing in this scenario.

I hope this discussion will lead to either a clarification of something I minsunderstood about smart-table or the addition of a welcome feature that is, ATM, missing.

**Comment by lorenzofox3** [comment]
Hi, 

> But what about external events that should trigger the pipe function ? In this case, I can't call my pipe 
> function with the tableState object, so I have no external way of setting the total number of pages 
> (which in turn should trigger the corresponding reload).

Actually smart-table is not designed so the pipe function is callable form outside and it should not be the case. The reason I am saying that is that it is already quite complicated to sync the different directives and the tableState, so if you have to sync with the eternal world it will add another layer of complexity. You can see think smart-table a bit like the  [flux](https://facebook.github.io/flux/docs/overview.html) architecture. 
1. Your store is the tableState + displayedCollection (and reference collection in some point)
2. Plugins (the view) can trigger a set of defined actions through the table controller api
3. table controller (which has both role dispatcher and store) modify the table state and the displayed collection
4. views re-render based on the table state

This rule may be broken by directives which have external bindings for configuration purpose: when the configuration changes they trigger an action. 

For the total of items, I don't think it makes sense as it is not part of a "view configuration" but rather specific to your dataset. When you change your logged in user, you somehow change your dataset. 
Normally these changes are handled by smart-table if you set the st-safe-src attribute but when you use a custom pipe function it is your responsibility to handle data set specific changes (smart-table cannot have any idea of what is going on your server). 

So if you don't want to break the cycle, as explained in #393 you have to write a plugin which monitors external changes and then trigger an action (the easiest one and most logic would be "please got to page 1"), you can argue that this plugin logic could be handled by the pagination plugin like in your pull request, but for me it is semantically incorrect that the paginations handles changes in dataset and that is why I do not consider it should be part of the core.

**Comment by matgardon** [comment]
I've finally chosen the plug-in approach as discussed (here) [https://github.com/lorenzofox3/Smart-Table/issues/393#issuecomment-107432407].

Thanks for your patience on this issue.

I still believe there should be a better solution, mainly because the solutions to handling this problem are too different if one have a server-side collection or a client-side one, and this makes for uncessary complicated notions to understand for the developer wanting to use smart-table.

But as it stands, it's still a good enough solution for me !

**Pull request closed without merging**
