### PR TITLE
Added previous and next page buttons to pagination template

### PR DESCRIPTION
**Pull request by davidyaha**
Added previous and next page buttons to pagination template

### CODE REVIEW

**Comment by stanleyxu2005** [comment]
+1. It will be great, if you can externalize the text of "first", "previous", "next" and "last", so that we can replace them with whatever we want. And a bit greedy to be similar to DataTable to have four button layout and two button layout.

**Comment by lorenzofox3** [comment]
I actually prefer to have the template as simple as possible and let the user the ability to override it. Otherwise after I merge this PR, I ll have people opening a new one because they want "next" in the next page button instead of ">" , etc :)

**Comment by davidyaha** [comment]
I think this is a basic feature whenever pagination is required.
It would have been great to get that out of the box..
Would you consider it if I will externalise the button text?

Thanks for the great work supporting this package!

**Comment by BobKurtis** [comment]
here is a nice pagination template i've worked up.
```html
<div >
	<p><a ng-click="selectPage(1)" onclick="btnFirst_Click();return false;">&larr;&larr;FIRST</a>||
	<a ng-click="selectPage((currentPage-1))"
		onclick="btnPrev_Click();return false;">&larr;PREV</a>&nbsp;<select
		id="pageNumList"><option
			ng-repeat="n in [] | range: numPages" ng-click="selectPage(n)"
			value="{{n}}">{{n}}</option></select>
	/{{numPages}}


	<a ng-click="selectPage((currentPage + 1))"
		onclick="btnNext_Click();return false;">NEXT&rarr;</a>||<a
		ng-click="selectPage(numPages)"
		onclick="btnLast_Click();return false;">LAST&rarr;&rarr;</a>
		</p>
</div>
```
```javascript
<script>
	function btnPrev_Click() {
		var selectedIndex = $("#pageNumList").prop("selectedIndex");
		if (selectedIndex > 0) {
			$("#pageNumList").prop("selectedIndex", selectedIndex - 1);
		}
	};
	function btnFirst_Click() {
		var selectedIndex = $("#pageNumList").prop("selectedIndex");
		$("#pageNumList").prop("selectedIndex", 0);

	};
	function btnNext_Click() {
		//  Note:  the JQuery "prop" function requires JQuery v1.6 or later
		var selectedIndex = $("#pageNumList").prop("selectedIndex");
		var itemsInDropDownList = $("#pageNumList option").length;
		//  If we're not already selecting the last item in the drop down list, then increment the SelectedIndex
		if (selectedIndex < (itemsInDropDownList - 1)) {
			$("#pageNumList").prop("selectedIndex", selectedIndex + 1);
		}
	};

	function btnLast_Click() {
		var selectedIndex = $("#pageNumList").prop("selectedIndex");
		var itemsInDropDownList = $("#pageNumList option").length;
		$("#pageNumList").prop("selectedIndex", (itemsInDropDownList - 1));

	};
</script>
```
</div>
<p>
	<a ng-click="selectPage(1)" onclick="btnFirst_Click();return false;">&larr;&larr;FIRST</a>||
	<a ng-click="selectPage((currentPage-1))"
		onclick="btnPrev_Click();return false;">&larr;PREV</a>&nbsp;<select
		id="pageNumList"><option
			ng-repeat="n in [] | range: numPages" ng-click="selectPage(n)"
			value="{{n}}">{{n}}</option></select> /{{numPages}} <a
		ng-click="selectPage((currentPage + 1))"
		onclick="btnNext_Click();return false;">NEXT&rarr;</a>||<a
		ng-click="selectPage(numPages)"
		onclick="btnLast_Click();return false;">LAST&rarr;&rarr;</a>
</p>

{{n}} is actually a dropdown with all the page numbers

**Comment by stanleyxu2005** [comment]
@davidyaha I'd suggest you change your code to an external pagination template, so that user can simply use that.
```
    <tfoot>
    <tr>
      <td class="text-center">
        <div st-pagination="" st-items-by-page="itemsByPage"
             st-template="path/to/your/pagination-custom.html"></div>
      </td>
    </tr>
    </tfoot>
```

**Comment by davidyaha** [comment]
@stanleyxu2005 In my own implementation that's what i've done. I would be happy to include that in a pull request if @lorenzofox3 would agree to it.

**Pull request closed without merging**
