### PR TITLE
Issue #245 Add possibility to group rows on a property

### PR DESCRIPTION
**Pull request by eirikbell**
Added st-group directive which takes in property to group on.
result transforms collection to an array which looks like:

```
[
  {
    key: 'grouped val 1',
    items: [
      ...
    ]
  },
  ...
]
```

See plunker:
http://plnkr.co/edit/Yq4TEc?p=preview

### CODE REVIEW

**Comment by lorenzofox3** [comment]
waou that is great Erik, 
few remarks:
1. Like in [this example](http://plnkr.co/edit/qg4y7mtd7nnXtlRlc6SF?p=preview), we might want the group predicate to be dynamic (I think, it can be easily done by modifying a bit the stGroup directive to watch the predicate)
2. I was wondering also, what is the expected behaviour when you add the pagination on top of it: do we want to group the displayed page (like in your impl and in the example mentioned above) or do we want to apply the pagination after the groups have been done ? that is an open question, I don't really know
3. If we have 1) to be consistant, we should be able to have a "normal" table display if there is not group predicate set ( I think it can be done with a conditional template like in the example I provided)
4. by adding the group state to the tableState we have to be careful if one is using a custom pipe function (which calls a server for instance), because any change in the table state might trigger a call to the pipe function, so a bit of manual testing has to be done here to make sure a change in the group predicate does not trigger a cascade of calls.

Last, what do you think are the main advantages/reasons the table module to provide a grouping api over an external filter like in the example I provided ? 

Thanks anyway, it looks promising !

Laurent

**Comment by eirikbell** [comment]
2. This is a tricky question, however when using together with sorting I guess displayed page makes the most sense, as else a whole group is displayed early due to the lowest value inside items collection, while many records with a lower value is displayed on later pages. Then again for the end user it might make more sense that everything inside a group is consistent, no matter how you sort the data. Looking at complexity and performance, displayed page is preferable though. If we were to group on the whole base collection, I guess we would need some sorting logic for the groups as well.

3. I agree.

The main problem with using filter is performance, especially in internet explorer when having a large dataset where each object has many properties, the digest cycle often occupy a whole cpu core as the grouping is constantly evaluated. If its part of the table state and only processed inside the pipe function, the grouping is only evaluated whenever something should change. On the quite complex dataset which was the reson I opened #245 , I actually ended up implementing my own pipe function to be able to handle the combination of sort, filter, paging and grouping.

**Comment by Oceanview5112** [comment]
eirikbell,
I know this is closed, but I just wanted to comment.  I love "Issue #245 Add possibility to group rows on a property"  it works great.  But I noticed that if you add paging. It it's based off the original filtered data.
I changed it to this, and it works great with paging
in this.pipe, I moved the
"if (group.predicate !== undefined){"
above
"if (pagination.number !== undefined) {"
and changed 
"output = groupByProperty(output || filtered, group.predicate);"
to
"filtered = groupByProperty(filtered, group.predicate);"

and it works beautifully(at least from what i noticed so far (: ), and pages by group key, so if your showing 20 records, it shows the 20 keys and the sub rows(if viewed).

Thanks again

**Comment by eirikb** [comment]
@Oceanview5112 do you have a working plunker (or similar) as an example?

**Comment by Oceanview5112** [comment]
@eirikb not at the moment. I'll get one up by the weekend.

**Comment by eirikb** [comment]
@Oceanview5112 That would be awesome. This is my current solution, which is not support for grouping, just a bunch of smart-tables grouped together: http://plnkr.co/edit/5oxmHV5Q2JIVGtxJLlwI?p=preview . I need paging pr group. I probably need paging for all the groups as well

**Comment by Oceanview5112** [comment]
@eirikb Here ya go. http://plnkr.co/edit/iGX5pqWONgLP8lj7sWQm?p=preview  
I just forked @eirikbell 's plunker. I just whipped it together, but I like your ng-class solution better for the +- for clicked.  the first link in index.html is the original, the next 2 I altered with paging. and Ive shown 2 different ways to show grouping, one with headers, and one without.  But the main piece to look at is smart-table.js line:172  that if statement was below paging. so it was setting pagination before it groupedByProperty

**Comment by eirikb** [comment]
Thanks @Oceanview5112, it really does work :+1: 
Compared to the angular-filter solution I see that paging works as it should, same with ordering (although ordering closes the groups, but that is perhaps by-design?)
Any idea on paging inside a group (similar to my hack)?
Here is your plunk, just with more rows: http://plnkr.co/edit/4o6KptR36uV0GeTOPoGR?p=preview , as you can see huge amounts of data can be troublesome

**Comment by Oceanview5112** [comment]
@eirikb Ahh, you're looking at some work there.  If I had use case for that, I'd be up for the challenge.  But I think you'd have to create another pagination directive where you can pass in each group array. then filter out the page results for each group. and redraw. It's definitely possible, but a little extra work to be done. Assuming you don't need to sort or filter each group, and you just wanted to search, filter, sort on all the groups, then just page inside the group array.  You'd only have to create a new custom pagination directive and custom pipe function that is independent and only based on the data passed in per group.

**Pull request closed without merging**
