### PR TITLE
Merged changes from lorenzofox3's "custom-filters" branch into master

### PR DESCRIPTION
**Pull request by benmj**
I incorporated the changes made in the "custom-filters" branch into the master branch. Trying to do a direct merge was causing a lot of conflicts (mostly whitespace), so I just manually recreated the changes in that branch.

All tests are still passing.

### CODE REVIEW

**Comment by cjmaio** [comment]
+1 for pulling this into master - this is something required for a project I am working on.

**Comment by lorenzofox3** [comment]
Actually I was not sure it was the best approach, you can still do custom filtering in other ways (cf discussion: https://github.com/lorenzofox3/Smart-Table/pull/221). I am still waiting for @https://github.com/Almar feedbacks as he was the one bringing up the topic, any particular thought on the topic

**Comment by cjmaio** [comment]
Testing with my application, the discussion in #221 helped, and using an Angular filter did exactly what I needed it to do, and it was easier than this implementation IMO.

**Comment by benmj** [comment]
@lorenzofox3 Thanks for your reply! Like @Almar, I'm working with a team of developers and would prefer to have a "simple" option in which all filters are declared independently of each other. I think the example you provided in #221 could be especially useful when we have larger tables and need a finer degree of control over filtering and speed.

That said, do you think there is a chance that this (or a solution like it) will make it into the master branch?

**Comment by Almar** [comment]
My apologies to @lorenzofox3, I promised to look at this proposal in #221 but never came around to do so. The thing is that I’m already using my own solution. Also my fork contains some other breaking features (I got rid of st-safe-src for instance) and I kind of accepted that these changes would never be part of the master. 

Now that I looked at your proposal I must say that I like it. I have one suggestion though, allow for an optional name for the comparator and make the comparator part of the table state. Having this information in a custom pipe function means that you can inform the server how the (query) data ought to be filtered. 

e.g. it would be great if a custom pipe method could make get parameters like:
?filterLike(firstName:Bla,lastName:Fai), filterExact(color:blue)

~ Almar

**Comment by lorenzofox3** [comment]
No worries, it is fine :) 

Actually I am not yet convinced it is worth to add 10% of the current codebase to achieve something you can already do.

@Almar. When you call the the search api you can pass whatever input you want. it does not have to be string, it can be an object as well. Also keep in mind the table state must remain serialisable. And any change on it can have side effects, especially when you use a custom pipe function (as an http call will likely happen every time you change the table state)

Also, I was interested in how you got rid of the st-safe-src and had a look at you repo. But for me it looks like you simply renamed it into st-src and made it mandatory whether the data set is static or not. So yo u still have two variables (one for the data source and one for display in the template). May I know what was your motivation ?

**Pull request closed without merging**
