### PR TITLE
Fixing a sort bug.

### PR DESCRIPTION
**Pull request by douglas-treadwell**
Adding tableState().sort.predicate.functionHash to avoid a bug in which stSort's $watch on sort does not fire when the predicate changes from one un-named function to another un-named function.

I encountered this bug today while using smart-table and this commit fixes it.

Angular apparently doesn't fire watches when only functions in an object change.  I remember reading about this somewhere, and confirmed it in my console.

### CODE REVIEW

**Comment by douglas-treadwell** [comment]
That sounds good.  I'll make the change and add tests.

**Comment by douglas-treadwell** [comment]
Oh, I remember why I didn't do that.  What if a user replaces one function named "customSort" with another function named "customSort"?  The watch wouldn't fire, and we leave ourselves with a different bug.

We could always use a function hash, but then we potentially lose some useful information.  I wasn't sure if the function name could be useful for debugging or other purposes.  If you don't want to keep that information, I would remove the functionName entirely and only use the functionHash.

**Comment by lorenzofox3** [comment]
Yes, I think always using a hash will be more consistent. Anyway, the corner case you mentioned would be really easy to workaround on user side. So not really a big deal in my opinion.

Thanks again for your contribution, I really appreciate ! :+1:

**Comment by douglas-treadwell** [comment]
I'll fix this up today.

**Comment by douglas-treadwell** [comment]
Okay, so my latest commit makes the change we discussed and adds/updates tests.  There are merge conflicts, but it's late so I'll take care of those another day, likely tomorrow.

**Comment by douglas-treadwell** [comment]
It had conflicts with my own other commits, because both were branched from lorenzofox3/master.  Rebase might also have solved the problem.

**Pull request closed without merging**
