### PR TITLE
Make plugin filters posible

### PR DESCRIPTION
**Pull request by Almar**
I would like to be able to filter the data in a table in more ways than just 'contains', like st-search does. Further more I would like to be able to filter different columns with different filter behaviors. For instance a column with a standard search, then a column with a date picker (or date range selector) and then a column with a select box that needs a strict comparison filter.

With this PR I would like to suggest a way to make filter plugins possible. Lets say I would like to make my own version of st-search that does a strict comparison. That's easy now, make your own directive based on st-search and change
```
var filter = ctrl.registerFilter('search');
```
into 
```
var filter = ctrl.registerFilter('myStrictFilter', true);
```
Maybe you would like to use a select box for selecting values in a range (\<10, 10-100, \>100), then
(example code, please don't copy)
```
var filter = ctrl.registerFilter('myRangeFilter', function(actual, expected){
  if (expected) {
    if (expected==='<10') {
      return actual < 10;
    }
    if (expected==='10-100') {
      return actual >=10 && actual <= 100;
    }
    if (expected==='>100') {
      return actual > 100;
    }
  }
 return true;
});
```

EDIT: This solution is now fully backwards compatible, no breaking changes to the API.

### CODE REVIEW

**Comment by joewired** [comment]
Your plunkr example above breaks on angular versions 1.3.6 and above. Specifically the date range.

**Comment by Almar** [comment]
Hey Laurent,

My apologies for never commenting on your custom-filters brach. I've looked at it now. I like it but do have some suggestions. I've added these on #360.

~ Almar

**Comment by japo32** [comment]
Hi Laurent. Ive been trying to use the plunker code and integrate it into my app. The problem is that when I change the angular version to 1.3.15 and put a console.log in the custom Comparator, the actual and expected have a value of undefined and the string value of the selected date. 
It has this rather than the string value pf the row date and an object containing before and after.
Heres my fork of the plunk thats got it working again but still in 1.3.15.
http://plnkr.co/edit/yy1aZNKR2GLdXhZ4XJzp

Any help would be appreciated. Id love to keep using smart table on this project, we just have to overcome this small hiccup.

**Comment by japo32** [comment]
Apologies for any typos as I'm typing this on my phone.

**Comment by japo32** [comment]
I've managed to make it work by not using $filter('filter')

http://plnkr.co/edit/yy1aZNKR2GLdXhZ4XJzp?p=preview

**Comment by murhum1** [comment]
@japo32, fiddled around with your plunker a bit since I felt like the search only firing on blur events didn't feel intuitive to use. I used ng-change and managed to fire the search every time the input field changes instead of only on blur events. Also changed it for the number filter.

http://plnkr.co/edit/8Cgmvrj8SOlmcZBGcepJ?p=preview

**Comment by japo32** [comment]
@murhum1, yes, that's what I eventually ended up using on the actual project. :) Glad to have helped.

**Pull request closed without merging**
