### PR TITLE
Add [href] to anchor tag in pagination template

### PR DESCRIPTION
**Pull request by chrisuehlinger**
Hey @lorenzofox3!

I've been using smart-table at work, and it's been awesome! I have one small accessibility bug fix: Without an `href` attribute, `<a>` tags cannot be selected using the keyboard and will not have the `cursor:pointer` style in most browsers.

Let me know if there's anything else you need me to do, and thanks again for the awesome library.

### CODE REVIEW

**Comment by lorenzofox3** [comment]
sounds good to me, however I would prefrer the href to point to a fragmented url ``href="#"`` rather than calling javascript

**Comment by chrisuehlinger** [comment]
Pointing the `href` to a hash like that can cause problems with client-side routing, and in some browsers scrolls the user to the top of the page.

**Comment by lorenzofox3** [comment]
good point

**Comment by RobJacobs** [comment]
Using href="javascript:void(0);" will fail Content Security Policy check: https://developer.mozilla.org/en-US/docs/Web/Security/CSP

We went through a sweep of the angular-ui-bootstrap library templates and use the <a href></a> approach and it has worked out fine.

**Comment by lorenzofox3** [comment]
yes you are right, I will revert the change. Thanks for the tip

**Pull request merged**
