### PR TITLE
totalItemCount property added to pagination object on tableState

### PR DESCRIPTION
**Pull request by eirikbell**
Added totalItemCount on tablestate pagination object and exposed on st-pagination scope.

This enables pagination templates with knowledge of total rows, to as example, display: Showing rows y-z of x

Here is an example template which shows usage:

```
<div>
    <div class="pages">
        <span class="pages-ellipsis pre" ng-if="pages[0] > 1">...</span>
        <nav ng-if="pages.length >= 2">
            <ul class="pagination">
                <li ng-repeat="page in pages" ng-class="{active: page==currentPage}">
                    <a ng-click="selectPage(page)">{{page}}</a>
                </li>
            </ul>
        </nav>
        <span class="pages-ellipsis post" ng-if="pages[pages.length - 1] * stItemsByPage < totalItemCount">...</span>
    </div>

    <div class="x-of-y">
        Showing {{(currentPage-1)*stItemsByPage+1}}-{{(currentPage)*stItemsByPage > totalItemCount ? totalItemCount : (currentPage)*stItemsByPage}} of {{totalItemCount}}
    </div>
</div>
```

### CODE REVIEW

**Comment by lorenzofox3** [comment]
Thanks !

I have not tried but I believe that if you expose it to the table state and use a custom pipe function you might trigger two calls when you filter:
one because tablestate.search changes and another one because tablestate.pagination changes. 

To be checked

**Comment by eirikbell** [comment]
I have only 1 grid where I use a custom pipe function, and it does not trigger multiple times. However you are yourself responsible for setting tableState.pagination.totalItemCount inside the custom pipe function if you wish to use it in template as this is currently done in the pipe function. This is intentional because the logic in your custom pipe function may be the only place where you may possibly know the total amount of records available from the server.

**Comment by eirikbell** [comment]
We have been using this in production for 3 months now without finding any issue with it. Any update on whether you will accept the pull request?

**Comment by lorenzofox3** [comment]
merged :+1: Thanks

**Pull request closed without merging**
