### PR TITLE
st-descending-first option for st-sort

### PR DESCRIPTION
**Pull request by douglas-treadwell**

### CODE REVIEW

**Comment by lorenzofox3** [comment]
great I will review that one thanks

**Comment by derwok** [comment]
HI! Thanks for this feature. Great work! I need it on some coulums...

Unfortunately if I combine this
     st-descending-first="true" with
     st-sort-default="reverse" like so:
`<th st-sort="Points" st-sort-default="reverse" st-descending-first="true" class="sortableColum">Points</th>`
The new feature (descending first) breaks the old feature (sort default).

**Comment by andy-dumbell** [comment]
+1 please

**Comment by cassiomansini** [comment]
same issue @derwok 
Do you remember if u could fix that 3 years ago?

**Comment by derwok** [comment]
Hi. 
Unfortunately I don’t remember exactly. Probably I just accepted it. It was a minor issue for me. 
Sorry for being of no more help.

**Comment by cassiomansini** [comment]
No prob. Thanks!

**Pull request merged**
