### PR TITLE
Added possibility to show in pagination first, previous, next, last, and collapsed pages buttons

### PR DESCRIPTION
**Pull request by llissssss**
Hey,

I added a few attributes/parameters to the st-pagination directive in order to be able to show first, previous, next, last, and collapsed pages buttons as an extra options for the pagination:
stFirstPage => expects a string to be displayed as first page button value. If not provided is not shown
stLastPage => expects a string to be displayed as last page button value. If not provided is not shown
stPrevPage => expects a string to be displayed as previous page button value. If not provided is not shown
stNextPage => expects a string to be displayed as next page button value. If not provided is not shown
stCollapsedPages => expects a boolean to show or not the collapsed pages icon [...]. By default is not shown.

I ran the tests and build it again and it seems to work.

As this is my first ever contribution, I hope everything is fine, and please don't hesitate to ask/correct me if something is not clear! :)

Cheers,

### CODE REVIEW

**Comment by mg1075** [comment]
+1
The pagination needs to be able to have the option for showing first and last.

**Comment by lorenzofox3** [comment]
and if you type "pagination template" in the issue search text box up there, you'll find quite a few related to the topic with some examples (http://plnkr.co/edit/e82rdx7R4pjbLvayUHXx?p=preview)
You actually have an example on the documentation website !

**Comment by llissssss** [comment]
Hey @lorenzofox3 ,

Thanks for your feedback. 

Actually, I have been following the issues and past pull requests regarding pagination, and because I still thinking it's a feature that should be supported out of the box (if wanted), I did that pull request that keeps the default behaviour adding a couple features with a few params.

And yes, now I see that there's an example in the documentation website, however this example wasn't there before (the pull request was merged on march 13th).

Anyway, if you change your mind at some point and you need it, I'll be more than happy to help.
Thanks again for your feedback and keep up the good work.

**Comment by viniciusaugutis** [comment]
If you still need:

Create a template html with the code below:

<div class="pagination">
  <ul class="pagination">
    <li ng-if="currentPage !== 1"><a ng-click="selectPage(currentPage - 1)" aria-label="Previous"><span aria-hidden="true">Anterior</span></a></li>
    <li ng-if="currentPage !== 1"><a ng-click="1 &lt; (currentPage - 5) ? selectPage(currentPage - 5) : selectPage(1)" aria-label="PreviousPoints"><span aria-hidden="true">...</span></a></li>
    <li ng-repeat="page in pages" ng-class="{active: page == currentPage}"><a ng-click="selectPage(page)">{{page}}</a></li>
    <li ng-if="currentPage !== numPages"><a ng-click="numPages &gt; (currentPage + 5) ? selectPage(currentPage + 5) : selectPage(numPages)" aria-label="NextPoints"><span aria-hidden="true">...</span></a></li>
    <li ng-if="currentPage !== numPages"><a ng-click="selectPage(currentPage + 1)" aria-label="Next"><span aria-hidden="true">Próximo</span></a></li>
  </ul>
</div>

And apply in your pagination:
div(st-pagination='', st-items-by-page = '10', st-displayed-pages='5', st-template="pagination.html")

**Pull request closed without merging**
