### PR TITLE
Avoid creating isolated scope for st-search directive

### PR DESCRIPTION
**Pull request by Toilal**
Creating an isolated scope for `st-search` directive makes it unsusable along with other directives that requires an isolated scope too.

This changes drops the scope creation, by using [Attributes.$observe](https://docs.angularjs.org/api/ng/type/$compile.directive.Attributes#$observe) instead of [scope.$watch](https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$watch)

My particular use case if to use `st-search` directive with angular-material [md-autocomplete](https://material.angularjs.org/#/demo/material.components.autocomplete), which creates an isolated scope too. Two directives can't be loaded on the same element if they both create a new scope.

I'm sorry, this is a BREAKING change, because `st-search` value is now [interpolated](https://docs.angularjs.org/api/ng/service/$interpolate), instead of [parsed as an expression](https://docs.angularjs.org/api/ng/service/$parse).

### CODE REVIEW

**Comment by lorenzofox3** [comment]
looks like we are going toward smart-table 2.0.0 ;) I'll take a bit of time to review that one, although I trust you. Do you want commit rights ?

**Comment by Toilal** [comment]
As you wan't, it would be great and I could review other issues/PR when I have free time :)

Could you give me access to website too, to update the docs when required ?

Thanks !

**Comment by Toilal** [comment]
It could be published on NPM too. For release management, I use [release-it](https://github.com/webpro/release-it). In one step, it tag on the repository, updates bower.json and npm.json with next version number, and upload to npmjs.org.

**Comment by Toilal** [comment]
BTW great work on the library :)

**Comment by lorenzofox3** [comment]
I don't forget you, just a bit busy at the moment ;)

**Pull request merged**
