### PR TITLE
Fix collection watching for stSafeSrc

### PR DESCRIPTION
**Pull request by sebek64**
Fixes watching of stSafeSrc, so that all changes to the observed collection are reflected.

### CODE REVIEW

**Comment by lorenzofox3** [comment]
Actually I don't even know what you try to fix but if the goal is to use the watchCollection please note that it is not wanted https://github.com/lorenzofox3/Smart-Table/issues/205

**Comment by sebek64** [comment]
Well, I understand the efficiency reasons for not using watchCollection by default. But it is not the same as deep watching, it is just a one-level deeper than now.

I'll try to describe what I'm trying to fix. Basically, the main problem is sorting. When an element is replaced by a different one, the current order may be wrong.

Yes, I agree that my solution does not work for everyone. If someone uses your workaround with angular.extend, then my change would not help with sorting.

So I'm suggesting a solution which I'm ready to write, if you'd agree to merge it. It'll take a bit more time than previous fixes. So if you won't accept my changes, I'll maintain my local changes and won't waste time writing a general solution.

I think there should be another optional attribute (eg. stSafeSrcWatchLevel or just watchLevel) with values like reference, reference-length, collection, deep. For reference, it'll do a simple watch. With reference-length, it'll do the same as now. For collection, it'll do a collection watch, and for deep, it'll do a deep watching. The default will be reference-length.

**Comment by lorenzofox3** [comment]
In your case the easiest would probably be to use st-safe-src attribute and re assign the watched collection so you are sure the sort is kicked on new values.

```Javascript
$scope.updateRow = (row, newRow) => {
  const index = $scope.rowCollection.indexOf(row);
  if(index !== -1) {
    const newDataSet = [...$scope.rowCollection];
    newDataSet.splice(index, 1, newRow);
    $scope.rowCollection = newDataSet; // assign new reference, the watch should be kicked
  }
}
```

I don't think setting as attribute the way things should be watched is a good thing to do, It is more related to angular internals and it seems to be already complicated to grasp with stSafeSrc attribute

**Comment by sebek64** [comment]
Yes, creating a collection copy and reassigning is my current solution, but it causes the pagination to reset on every change, which is ugly.

**Comment by lorenzofox3** [comment]
and what if you add the new row, then remove the old one

```Javascript
$scope.updateRow = (row, newRow) => {
  const index = $scope.rowCollection.indexOf(row);
  if(index !== -1) {
    $scope.rowCollection.splice(index, 0, newRow);
    $scope.rowCollection.splice(index+1,1);
  }
}
```

?

**Comment by lorenzofox3** [comment]
you'll probably have to remove the old one on the next tick though

**Comment by sebek64** [comment]
Yes, that would probably work. I'll test it on Monday and discuss this change with my colleague if it is better than maintaining a fork of smart table.

**Comment by lorenzofox3** [comment]
I think the watch collection would probably be the best for your use case, but harmful for people using big pages

**Pull request closed without merging**
